shoot4fun:
  images:
    server:
      tag: latest
      repository: ghcr.io/psa-department-of-engineering/shoot4fun-server
    client:
      tag: latest
      repository: ghcr.io/psa-department-of-engineering/shoot4fun-client
  database:
    secret: pg-app-shoot4fun
