apiVersion: v2
name: shoot4fun
description: prod environment pin for shoot4fun (ADR-025 deploy branch).
type: application
version: 1.0.2
dependencies:
  - name: shoot4fun
    version: 1.0.2
    repository: oci://ghcr.io/psa-department-of-engineering/charts
