apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoot4fun.name" . }}-docs
  labels:
    app: {{ include "shoot4fun.name" . }}-docs
spec:
  selector:
    app: {{ include "shoot4fun.name" . }}-docs
  ports:
    - port: {{ .Values.docs.port }}
      targetPort: {{ .Values.docs.port }}