apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoot4fun.name" . }}-server
  labels:
    app: {{ include "shoot4fun.name" . }}-server
spec:
  selector:
    app: {{ include "shoot4fun.name" . }}-server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
